# Generated by Django 3.0.1 on 2020-06-24 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ip',
            new_name='address',
        ),
    ]
