# Generated by Django 3.0.6 on 2020-05-22 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200522_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cnt_comment',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 14, 42, 26, 767792, tzinfo=utc)),
        ),
    ]
