# Generated by Django 3.0.6 on 2020-05-22 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200522_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 14, 45, 55, 681855, tzinfo=utc)),
        ),
    ]
